export default class SearchMockData {
  static async getData() {
    let bestMatches = this.getMockData();
    return bestMatches;
  }

  static getMockData() {
    return [
      {
        "1. symbol": "MOCK-IBM",
        "2. name": "International Business Machines Corporation",
        "3. type": "Equity",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-05",
        "8. currency": "USD",
        "9. matchScore": "1.0000",
      },
      {
        "1. symbol": "MOCK-IBMM",
        "2. name": "iShares iBonds Dec 2024 Term Muni Bond ETF",
        "3. type": "ETF",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-05",
        "8. currency": "USD",
        "9. matchScore": "0.8571",
      },
      {
        "1. symbol": "MOCK-IBMK",
        "2. name": "iShares iBonds Dec 2022 Term Muni Bond ETF",
        "3. type": "ETF",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-05",
        "8. currency": "USD",
        "9. matchScore": "0.8571",
      },
      {
        "1. symbol": "MOCK-IBMP",
        "2. name": "iShares iBonds Dec 2027 Term Muni Bond ETF",
        "3. type": "ETF",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-05",
        "8. currency": "USD",
        "9. matchScore": "0.8571",
      },
      {
        "1. symbol": "MOCK-IBMI",
        "2. name": "iShares iBonds Sep 2020 Term Muni Bond ETF",
        "3. type": "ETF",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-05",
        "8. currency": "USD",
        "9. matchScore": "0.8571",
      },
      {
        "1. symbol": "MOCK-IBMN",
        "2. name": "iShares iBonds Dec 2025 Term Muni Bond ETF",
        "3. type": "ETF",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-05",
        "8. currency": "USD",
        "9. matchScore": "0.8571",
      },
      {
        "1. symbol": "MOCK-IBMJ",
        "2. name": "iShares iBonds Dec 2021 Term Muni Bond ETF",
        "3. type": "ETF",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-05",
        "8. currency": "USD",
        "9. matchScore": "0.8571",
      },
      {
        "1. symbol": "MOCK-IBMO",
        "2. name": "iShares iBonds Dec 2026 Term Muni Bond ETF",
        "3. type": "ETF",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-05",
        "8. currency": "USD",
        "9. matchScore": "0.8571",
      },
      {
        "1. symbol": "MOCK-IBML",
        "2. name": "iShares iBonds Dec 2023 Term Muni Bond ETF",
        "3. type": "ETF",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-05",
        "8. currency": "USD",
        "9. matchScore": "0.8571",
      },
    ];
  }
}
